### ISSUE TITLE
warning while building the docs

### ISSUE THREAD

**Issue by shivangvijay** [ControlCore-Project/documentation#12]
While build the docs, it shows lots of warning message.
![Screenshot from 2023-05-13 16-48-49](https://github.com/ControlCore-Project/documentation/assets/36565630/3eab6e6c-5117-442e-a22a-19f3a53841a8)

**Comment by shivangvijay** [comment]
Check pull request #13

**Comment by pradeeban** [comment]
Merged. Thanks.
